# my bashrc file

source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/alias
source ~/bin/dotfiles/bash/prompt

############# rvm setup #############
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
eval "$(rbenv init -)"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
